- hosts: all
  become: false
  tasks:
    - name: debug
      debug:
        msg: "{{ ansible_env.HOME }} {{ lookup('ENV', 'HOME') }}"
    - name: HOME settings
      copy:
        src: "{{ lookup('ENV', 'HOME') }}/{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
      loop:
        - ".aws/"
        - ".git-credentials"
        - ".bash_lab_completion"
    - name: git config
      command: git config --global {{ item.name }} {{ item.value }}
      loop:
        - name: user.email
          value: yuusuke.kounoike@futurestandard.co.jp
        - name: user.name
          value: KOUNOIKE Yuusuke
        - name: credential.helper
          value: store
    - name: ghq get
      command: /go/bin/ghq get {{ item }}
      loop:
        - https://gitlab.com/futurestandard/algorithms/sensevideo
        - https://gitlab.com/futurestandard/algorithms/yolo_with_tracking
    - name: bashrc
      blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          alias ghqgo='cd $(ghq root)/$(ghq list | peco)'
          alias ghqcode='code $(ghq root)/$(ghq list | peco)'
          alias ghqlabget='ghq get https://gitlab.com/$(lab project list -m | peco)'
          [ -e /usr/local/etc/bash_completion ] && source /usr/local/etc/bash_completion
          [ -e $HOME/.bash_lab_completion ] && source $HOME/.bash_lab_completion
